// Generated by CoffeeScript 1.4.0

/*
Helper that takes a potential mongo error and translates it into something more tangible.
*/


(function() {
  var FieldValidationError, UniquenessValidationError, _;

  _ = require('underscore');

  UniquenessValidationError = require('./uniqueness-validation-error');

  FieldValidationError = require('./field-validation-error');

  module.exports = function(err, resource) {
    var e, key, xx, _i, _len, _ref;
    if (resource == null) {
      resource = null;
    }
    if (!err) {
      return err;
    }
    if (err.name === "MongoError") {
      if (err.err.indexOf("E11000") >= 0) {
        return new UniquenessValidationError(resource, []);
      }
    } else if (err.name === "ValidationError" && !err.status) {
      xx = [];
      _ref = _.keys(err.errors || {});
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        key = _ref[_i];
        e = err.errors[key];
        xx.push({
          resource: resource,
          field: e.path,
          code: e.type,
          message: e.message
        });
      }
      return new FieldValidationError(resource, xx);
    }
    return err;
  };

}).call(this);
